services:
  marzban:
    container_name: marzban
    image: gozargah/marzban:v0.2.6
    restart: always
    env_file: .env
    environment:
      SQLALCHEMY_DATABASE_URL: "sqlite:////data/db.sqlite3"
      XRAY_JSON: "/xray_config.json"
    ports:
      - "8899:8880" # Port Panel Marzban
    volumes:
      - ./marzban/xray_config.json:/xray_config.json
      - marzban_data:/data         
    networks:
      - marzban_net

  nginx:
    container_name: nginx-reverse
    image: nginx:alpine
    restart: always
    ports:
      - "8818:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./xray.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/xray/xray.crt:/etc/xray/xray.crt:ro
      - /etc/xray/xray.key:/etc/xray/xray.key:ro
      - /home/vps/public_html:/home/vps/public_html
    depends_on:
      - marzban
    networks:
      - marzban_net

  cloudflared:
    image: cloudflare/cloudflared:latest
    env_file: .env
    restart: always
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - nginx
      - marzban
    networks:
      - marzban_net

networks:
  marzban_net:
    driver: bridge

volumes:
  marzban_data:
