services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./cert:/etc/letsencrypt
      - ./cert/lib:/var/lib/letsencrypt
      - ./cert/xray:/xray
    ports:
      - "80:80" # Port for HTTP challenge
    entrypoint: /bin/sh
    command: -c "
      mkdir -p /xray && \
      certbot certonly --standalone --preferred-challenges http \
      --non-interactive --agree-tos \
      --email ${CERTBOT_EMAIL} \
      -d ${CERTBOT_HOSTNAME} && \
      cp /etc/letsencrypt/live/${CERTBOT_HOSTNAME}/fullchain.pem /xray/xray.crt && \
      cp /etc/letsencrypt/live/${CERTBOT_HOSTNAME}/privkey.pem /xray/xray.key
      "

  marzban:
    container_name: marzban
    image: gozargah/marzban:v0.2.6
    restart: always
    env_file: .env
    environment:
      SQLALCHEMY_DATABASE_URL: "sqlite:////data/db.sqlite3"
      XRAY_JSON: "/xray_config.json"
    ports:
      - "8899:8880" # Port Panel Marzban
      - "2016:2016" # Port Shadow Sock
    volumes:
      - ./marzban/xray_config.json:/xray_config.json
      - marzban_data:/data         
    networks:
      - marzban_net

  nginx:
    container_name: nginx-reverse
    image: nginx:alpine
    restart: always
    ports:
      - "8818:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./xray.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cert/xray/xray.crt:/etc/xray/xray.crt:ro
      - ./cert/xray/xray.key:/etc/xray/xray.key:ro
      - /home/vps/public_html:/home/vps/public_html
    depends_on:
      - marzban
    networks:
      - marzban_net

  cloudflared:
    image: cloudflare/cloudflared:latest
    env_file: .env
    restart: always
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - nginx
      - marzban
    networks:
      - marzban_net

networks:
  marzban_net:
    driver: bridge

volumes:
  marzban_data:
